# Generated by Django 4.2.7 on 2024-05-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatform',
            old_name='wwebsite',
            new_name='website',
        ),
    ]
